version: "3.9"

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OPENAI_API_KEY="dummy"
    volumes:
      - open-webui:/app/backend/data
    restart: always

  litellm-proxy:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm-proxy
    ports:
      - "4000:4000"
    environment:
      AZURE_API_KEY: ${AZURE_API_KEY}
      AZURE_API_BASE: ${AZURE_API_BASE}
      AZURE_API_VERSION: ${AZURE_API_VERSION}
      AZURE_MODEL_NAME: ${AZURE_MODEL_NAME}
    env_file:
      - .env
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
    command: --config /app/config.yaml --detailed_debug

volumes:
  open-webui:
